# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'QtSsLocationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
#
# File committed to retain a record of modifications made to it after
# automatic generation from QtSsLocationDialog.ui These changes include
# * Qt imports from PySide2
# * Addition of QDoubleValidator objects to latitude and longitude input
# * Set initial focus to the latitude input
#
# Version: 1.0
# Copyright (C) 2020/09/21 David A. Mair
# This file is part of QtSunsetter<https://github.com/mairda/QtSunsetter.git>.
#
# QtSunsetter is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# QtSunsetter is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with QtSunsetter.  If not, see <http://www.gnu.org/licenses/>.

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_QtSsDialog(object):
    def setupUi(self, QtSsDialog):
        QtSsDialog.setObjectName("QtSsDialog")
        QtSsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        QtSsDialog.resize(286, 234)
        self.buttonBox = QtWidgets.QDialogButtonBox(QtSsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 182, 266, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(QtSsDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(QtSsDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 39, 46, 16))
        self.label_2.setObjectName("label_2")
        self.longitude = QtWidgets.QLineEdit(QtSsDialog)
        self.longitude.setGeometry(QtCore.QRect(82, 68, 120, 30))
        self.longitude.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.longitude.setMaxLength(16)
        self.longitude.setObjectName("longitude")
        self.longVDator = QtGui.QDoubleValidator()
        self.longVDator.setBottom(0.0)
        self.longVDator.setTop(180.0)
        self.longitude.setValidator(self.longVDator)
        self.label_3 = QtWidgets.QLabel(QtSsDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 75, 56, 16))
        self.label_3.setObjectName("label_3")
        self.latitude = QtWidgets.QLineEdit(QtSsDialog)
        self.latitude.setGeometry(QtCore.QRect(82, 32, 120, 30))
        self.latitude.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.latitude.setMaxLength(16)
        self.latitude.setObjectName("latitude")
        self.latVDator = QtGui.QDoubleValidator()
        self.latVDator.setBottom(0.0)
        self.latVDator.setTop(90.0)
        self.latitude.setValidator(self.latVDator)
        self.latDirection = QtWidgets.QComboBox(QtSsDialog)
        self.latDirection.setGeometry(QtCore.QRect(208, 32, 68, 30))
        self.latDirection.setObjectName("latDirection")
        self.latDirection.addItem("")
        self.latDirection.addItem("")
        self.longDirection = QtWidgets.QComboBox(QtSsDialog)
        self.longDirection.setGeometry(QtCore.QRect(208, 68, 68, 30))
        self.longDirection.setObjectName("longDirection")
        self.longDirection.addItem("")
        self.longDirection.addItem("")
        self.label_4 = QtWidgets.QLabel(QtSsDialog)
        self.label_4.setGeometry(QtCore.QRect(10, 111, 129, 16))
        self.label_4.setObjectName("label_4")
        self.tzOffset = QtWidgets.QSpinBox(QtSsDialog)
        self.tzOffset.setGeometry(QtCore.QRect(145, 104, 49, 30))
        self.tzOffset.setMinimum(-12)
        self.tzOffset.setMaximum(12)
        self.tzOffset.setProperty("value", 0)
        self.tzOffset.setObjectName("tzOffset")
        self.chkCorrectForSysTZ = QtWidgets.QCheckBox(QtSsDialog)
        self.chkCorrectForSysTZ.setGeometry(QtCore.QRect(10, 145, 203, 20))
        self.chkCorrectForSysTZ.setObjectName("chkCorrectForSysTZ")

        self.retranslateUi(QtSsDialog)
        self.buttonBox.accepted.connect(QtSsDialog.accept)
        self.buttonBox.rejected.connect(QtSsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(QtSsDialog)
        QtSsDialog.setTabOrder(self.latitude, self.latDirection)
        QtSsDialog.setTabOrder(self.latDirection, self.longitude)
        QtSsDialog.setTabOrder(self.longitude, self.longDirection)
        self.latitude.setFocus(QtCore.Qt.OtherFocusReason)

    def retranslateUi(self, QtSsDialog):
        _translate = QtCore.QCoreApplication.translate
        QtSsDialog.setWindowTitle(_translate("QtSsDialog", "Dialog"))
        self.label.setText(_translate("QtSsDialog", "Location:"))
        self.label_2.setText(_translate("QtSsDialog", "Latitude:"))
        self.label_3.setText(_translate("QtSsDialog", "Longitude:"))
        self.latDirection.setItemText(0, _translate("QtSsDialog", "North"))
        self.latDirection.setItemText(1, _translate("QtSsDialog", "South"))
        self.longDirection.setItemText(0, _translate("QtSsDialog", "East"))
        self.longDirection.setItemText(1, _translate("QtSsDialog", "West"))
        self.label_4.setText(_translate("QtSsDialog", "Timezone Offset (Hours):"))
        self.chkCorrectForSysTZ.setText(_translate("QtSsDialog", "Correct for system clock timezone"))
